awk: (FILENAME=gencode.v19.annotation.chr22.transcript.gtf FNR=76) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.gtf FNR=73) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.gtf FNR=83) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.fasta FNR=84) fatal: print to "standard output" failed (Broken pipe)
Hello I am a message in standard error (stderr)
